### ISSUE TITLE
[FEATURE] support `lts/` aliases for `engines.node` field in `package.json`

### ISSUE THREAD

**Issue by DerekNonGeneric** [npm/npm-install-checks#29]
The `engines.node` field in `package.json` does not currently support (or understand) the `lts/` aliases understood by runtime version management tools like [`nvm.bash`](https://github.com/nvm-sh/nvm), [`nvm.fish`](https://github.com/jorgebucaran/nvm.fish), and others (often seen specified in `.nvmrc` and `.node-version` files).

> For example, to make nvm default to the latest 5.9 release, the latest LTS version, or the latest node version for the current directory:
>
> ```console
> $ echo "5.9" > .nvmrc
>
> $ echo "lts/*" > .nvmrc # to default to the latest LTS version
>
> $ echo "node" > .nvmrc # to default to the latest version
> ```
>
> &mdash; https://github.com/nvm-sh/nvm#nvmrc

The only thing remotely close supported by npm seems to be `*`&hellip;

> And, like with dependencies, if you don't specify the version (or if you specify "*" as the version), then any version of node will do.
> &mdash; https://docs.npmjs.com/cli/v8/configuring-npm/package-json#engines

I would find it quite useful to be able to specify `"lts/*"` for the value of the `engines.node` field in `package.json` files defaulting to the latest LTS version and never have to think about this again. 

Currently, we have to keep tabs on this field every time an LTS release line goes EOL (potentially dropping support) and every time an even-numbered Node.js version release line gets promoted to LTS (typically adding the SemVer range signifying support).

This can become quite tedious, as one can imagine. Any interest in supporting this convention?

/cc @ljharb @isaacs @darcyclarke

**Comment by wraithgar** [comment]
That information is encoded in the json returned from `https://nodejs.org/dist/index.json`.  It would have to be fetched and parsed on every install/update.  That's a pretty big addition to the install process.  Something this big definitely needs to go through the [rfc](https://github.com/npm/rfcs) process.

**Comment by DerekNonGeneric** [comment]
>  It would have to be fetched and parsed on every install/update.

I think this could be done efficiently so as not to affect performance unnecessarily. Looking at an old feature request by @isaacs, in the CLI repo at https://github.com/npm/cli/issues/4293 seems like it could be leveraged to determine whether there are any engine restrictions specified in the tree at all. If there are none, such a fetching sub-procedure would never need to run.

One of the biggest pain points has really been trying to keep up with whatever is considered to be [`maintained node versions`](https://github.com/browserslist/browserslist#full-list), which is actually a `.browserslistrc` thing and what the vast majority of packages likely intend to support. Abstracting that away in a single line would be great IMHO.

> also there’s no “nvm.bash”, it’s just nvm :-)

True, my bad, went ahead and fixed that above. ^^
